#!/bin/bash
# Quick Reference - Agro Nexus Connect Commands

echo "═══════════════════════════════════════════════════════════"
echo "  Agro Nexus Connect - Quick Start Commands"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTATION:"
echo "  - SETUP.md                    Complete setup guide"
echo "  - IMPLEMENTATION_SUMMARY.md   What was built"
echo "  - BACKEND.md                  API specification"
echo "  - backend/README.md           Backend guide"
echo ""
echo "🗄️  DATABASE (Terminal 1):"
echo "  cd backend"
echo "  docker-compose up -d          Start PostgreSQL"
echo "  npm run db:sync               Create tables"
echo "  npm run db:seed               Add sample data"
echo ""
echo "🔌 BACKEND (Terminal 1 after DB):"
echo "  cd backend"
echo "  npm install                   Install dependencies"
echo "  npm run dev                   Start server (port 4000)"
echo ""
echo "  Test backend health:"
echo "  curl http://localhost:4000/api/health"
echo ""
echo "🎨 FRONTEND (Terminal 2):"
echo "  cd /workspaces/agro-nexus-connect"
echo "  npm install                   Install dependencies"
echo "  npm run dev                   Start app (port 8080)"
echo ""
echo "📱 OPEN IN BROWSER:"
echo "  Frontend: http://localhost:8080"
echo "  Backend Health: http://localhost:4000/api/health"
echo ""
echo "🔐 TEST ACCOUNTS:"
echo "  Email: john@example.com       Farmer"
echo "  Email: mary@example.com       Farmer"
echo "  Email: buyer@example.com      Buyer"
echo "  Password: password123         (all users)"
echo ""
echo "🧪 TEST API ENDPOINTS:"
echo "  curl http://localhost:4000/api/health"
echo "  curl http://localhost:4000/api/products"
echo "  curl http://localhost:4000/api/farmers"
echo ""
echo "⚙️  USEFUL COMMANDS:"
echo "  npm run db:sync               Resync database tables"
echo "  npm run db:seed               Reseed sample data"
echo "  docker-compose down           Stop database"
echo "  docker-compose down -v        Stop & remove volume"
echo ""
echo "📋 API ENDPOINTS (base: /api):"
echo "  Authentication:"
echo "    POST /auth/register"
echo "    POST /auth/login"
echo "  Products:"
echo "    GET /products"
echo "    POST /products (farmers)"
echo "  Farmers:"
echo "    GET /farmers"
echo "    GET /farmers/dashboard (farmers)"
echo "  Orders:"
echo "    GET /orders"
echo "    POST /orders"
echo "  Reviews:"
echo "    GET /reviews/:productId"
echo "    POST /reviews"
echo ""
echo "═══════════════════════════════════════════════════════════"
